plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.netty:netty-all:4.1.4.Final'
    implementation 'org.rocksdb:rocksdbjni:10.10.1.1'
    implementation 'org.apache.kafka:kafka-clients:4.3.1'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}